import "./globals.css"


import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

const gtmScript1 = `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NFT9CPC')`

export const metadata = {
  title: "Download Terra | Terra Delete User",
  // description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" >
      <head>
      <script dangerouslySetInnerHTML={{__html:`${gtmScript1}`}}></script>
      </head>
      <body  className={inter.className}>{children}</body>
    </html>
  )
}
